<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="40" ignored="0" total="88" passed="48">
  <reporter-output>
  </reporter-output>
  <suite name="PageObjectTest Example" duration-ms="426618" started-at="2024-04-26T20:08:50 ICT" finished-at="2024-04-26T20:15:56 ICT">
    <groups>
    </groups>
    <test name="AutomationTest" duration-ms="426618" started-at="2024-04-26T20:08:50 ICT" finished-at="2024-04-26T20:15:56 ICT">
      <class name="projectss.testcases.MetaTest">
        <test-method status="PASS" signature="initializeTestBaseSetup(java.lang.String,java.lang.String)[pri:0, instance:projectss.testcases.MetaTest@5a1c0542]" name="initializeTestBaseSetup" is-config="true" duration-ms="5810" started-at="2024-04-26T20:08:50 ICT" finished-at="2024-04-26T20:08:55 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://wds.samsung.com/wds/sso/login/forwardLogin.do]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:projectss.testcases.MetaTest@5a1c0542]" name="setUp" is-config="true" duration-ms="0" started-at="2024-04-26T20:08:55 ICT" finished-at="2024-04-26T20:08:55 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="signIn()[pri:1, instance:projectss.testcases.MetaTest@5a1c0542]" name="signIn" duration-ms="5279" started-at="2024-04-26T20:08:55 ICT" finished-at="2024-04-26T20:09:01 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5738" started-at="2024-04-26T20:09:01 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:06 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh43bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh43bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh43bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="10163" started-at="2024-04-26T20:09:06 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:17 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh50bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh50bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh50bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6049" started-at="2024-04-26T20:09:17 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:23 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh55bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh55bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh55bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4605" started-at="2024-04-26T20:09:23 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:27 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh65bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh65bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh65bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3227" started-at="2024-04-26T20:09:27 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:30 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh75bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh75bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh75bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3402" started-at="2024-04-26T20:09:30 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:34 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh85bechlgkxxm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh85bechlgkxxm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/bec-h-biztv-uhd-4k-biztv-lh85bechlgkxxm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4650" started-at="2024-04-26T20:09:34 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:38 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/flip-pro-wm85b-interactive-display-lh85wmbwlgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/flip-pro-wm85b-interactive-display-lh85wmbwlgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/flip-pro-wm85b-interactive-display-lh85wmbwlgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3796" started-at="2024-04-26T20:09:38 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:42 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qbc-lh55qbcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3514" started-at="2024-04-26T20:09:42 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:46 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qbc-lh75qbcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3812" started-at="2024-04-26T20:09:46 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:50 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-lh43qmcepgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-lh43qmcepgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-lh43qmcepgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6116" started-at="2024-04-26T20:09:50 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:09:56 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-85-inch-lh85qmcebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-85-inch-lh85qmcebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qmc-85-inch-lh85qmcebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3857" started-at="2024-04-26T20:09:56 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:00 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/smart-signage-qm32c-lh32qmcepgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/smart-signage-qm32c-lh32qmcepgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/smart-signage-qm32c-lh32qmcepgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3870" started-at="2024-04-26T20:10:00 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:03 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/stretched-display-sh37c-lh37shcebgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3613" started-at="2024-04-26T20:10:03 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:07 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc5bgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc5bgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc5bgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3370" started-at="2024-04-26T20:10:07 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:10 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc3bgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc3bgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/samsung-kiosk-with-windows-os-lh24kmc3bgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3455" started-at="2024-04-26T20:10:10 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:14 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/km24a-lh24kmatbgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/km24a-lh24kmatbgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/km24a-lh24kmatbgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3951" started-at="2024-04-26T20:10:14 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:18 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/interactive-display-wac-lh65wacwlgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4785" started-at="2024-04-26T20:10:18 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:23 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/interactive-display-wac-lh75wacwlgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3961" started-at="2024-04-26T20:10:23 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:27 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb24c-t-small-digital-signage-lh24qbctbgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb24c-t-small-digital-signage-lh24qbctbgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb24c-t-small-digital-signage-lh24qbctbgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3814" started-at="2024-04-26T20:10:27 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:30 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/qm32r-b-lh32qmrbbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3513" started-at="2024-04-26T20:10:30 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:34 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/qb24c-small-digital-signage-lh24qbcebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/qb24c-small-digital-signage-lh24qbcebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/qb24c-small-digital-signage-lh24qbcebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6912" started-at="2024-04-26T20:10:34 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:41 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/all-in-one-led-iac-series-lh015iacchs-xs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/indoor-led/all-in-one-led-iac-series-lh015iacchs-xs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/indoor-led/all-in-one-led-iac-series-lh015iacchs-xs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3367" started-at="2024-04-26T20:10:41 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:44 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qhc-43-inch-lh43qhcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3185" started-at="2024-04-26T20:10:44 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:47 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qhc-50-inch-lh50qhcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3565" started-at="2024-04-26T20:10:47 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:51 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qhc-55-inch-lh55qhcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3285" started-at="2024-04-26T20:10:51 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:54 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qhc-65-inch-lh65qhcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3749" started-at="2024-04-26T20:10:54 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:10:58 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/crystal-uhd-signage-qhc-75-inch-lh75qhcebgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3955" started-at="2024-04-26T20:10:58 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:02 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-2400nit-flexible-installation-lh020ifrcls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4535" started-at="2024-04-26T20:11:02 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:06 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-2400nit-flexible-installation-lh025ifrcls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3368" started-at="2024-04-26T20:11:06 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:10 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-2400nit-flexible-installation-lh040ifrcls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="7070" started-at="2024-04-26T20:11:10 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:17 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-1600nit-flexible-installation-lh015ifrcls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3647" started-at="2024-04-26T20:11:17 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:21 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-indoor-led-p25-lh025ieacls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3975" started-at="2024-04-26T20:11:21 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:25 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-f-indoor-led-p25-lh025ieacfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3401" started-at="2024-04-26T20:11:25 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:28 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-f-indor-led-p40-lh040ieacfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3524" started-at="2024-04-26T20:11:28 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:31 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-f-indoor-led-p15-lh015ieacfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6140" started-at="2024-04-26T20:11:31 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:38 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-indoor-led-p15-lh015ieacls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6423" started-at="2024-04-26T20:11:38 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:44 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-f-indoor-led-p20-lh020ieacfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3496" started-at="2024-04-26T20:11:44 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:47 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-indoor-led-p20-lh020ieacls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5607" started-at="2024-04-26T20:11:47 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:53 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/iea-indoor-led-p40-lh040ieacls-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5884" started-at="2024-04-26T20:11:53 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:11:59 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/indoor-vm029r-i-lh029vmrsac-xm]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3701" started-at="2024-04-26T20:11:59 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:03 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/indoor-vm026r-i-lh026vmrsac-xm]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4797" started-at="2024-04-26T20:12:03 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:07 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-f-1600nit-flexible-installation-lh015ifrcfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3568" started-at="2024-04-26T20:12:07 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:11 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-f-1600nit-flexible-installation-lh020ifrcfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3322" started-at="2024-04-26T20:12:11 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:14 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-f-2400nit-flexible-installation-lh025ifrcfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4753" started-at="2024-04-26T20:12:14 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:19 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/indoor-led/ifr-f-2400nit-flexible-installation-lh040ifrcfs-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="11294" started-at="2024-04-26T20:12:19 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:30 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa067t-lh067xatsac-xm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa067t-lh067xatsac-xm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa067t-lh067xatsac-xm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5908" started-at="2024-04-26T20:12:30 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:36 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa160t-lh160xatsac-xm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa160t-lh160xatsac-xm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa160t-lh160xatsac-xm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3162" started-at="2024-04-26T20:12:36 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:39 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa100t-lh100xatsac-xm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa100t-lh100xatsac-xm expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xa100t-lh100xatsac-xm expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6001" started-at="2024-04-26T20:12:39 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:46 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/display-accessories/stn-km24a-stn-km24axxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3529" started-at="2024-04-26T20:12:46 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:49 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh012iabmhs-xs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh012iabmhs-xs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh012iabmhs-xs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="9819" started-at="2024-04-26T20:12:49 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:12:59 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh008iabmus-xs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh008iabmus-xs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh008iabmus-xs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3121" started-at="2024-04-26T20:12:59 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:02 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh016iabmhs-xs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh016iabmhs-xs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/led-signage/the-wall/the-wall-all-in-one-lh016iabmhs-xs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4220" started-at="2024-04-26T20:13:02 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:06 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/outdoor-signage-oh55a-s-fhd-4k-3500nit-ip5x-lh55ohaosgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6132" started-at="2024-04-26T20:13:06 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:12 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/outdoor-signage-oh46b-s-fhd-3500nit-ip5x-lh46ohbesgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4496" started-at="2024-04-26T20:13:12 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:17 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-s-4000nit-24hr-ip5x-lh55omnesgbxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-s-4000nit-24hr-ip5x-lh55omnesgbxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-s-4000nit-24hr-ip5x-lh55omnesgbxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3951" started-at="2024-04-26T20:13:17 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:21 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qmb-t-uhd-4k-capacitive-touch-8ms-lh43qmbtbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5828" started-at="2024-04-26T20:13:21 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:27 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qmb-t-uhd-4k-capacitive-touch-8ms-lh55qmbtbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="7266" started-at="2024-04-26T20:13:27 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:34 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-u-fhd-1080p-500nit-ip5x-35mm-lh55vmbubgbxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-u-fhd-1080p-500nit-ip5x-35mm-lh55vmbubgbxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-u-fhd-1080p-500nit-ip5x-35mm-lh55vmbubgbxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5960" started-at="2024-04-26T20:13:34 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:40 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/qbr-b-fhd-1080p-250nit-ip5x-lh24qbrbbgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/qbr-b-fhd-1080p-250nit-ip5x-lh24qbrbbgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/others/qbr-b-fhd-1080p-250nit-ip5x-lh24qbrbbgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6795" started-at="2024-04-26T20:13:40 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:47 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qbb-quantum-processor-4k-signage-lh55qbbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qbb-quantum-processor-4k-signage-lh55qbbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qbb-quantum-processor-4k-signage-lh55qbbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="8124" started-at="2024-04-26T20:13:47 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:13:55 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qm32r-t-lh32qmrtbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="6275" started-at="2024-04-26T20:13:55 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:01 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xrb-outdoor-led-5000nit-lh039xrbcxc-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3697" started-at="2024-04-26T20:14:01 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:05 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/outdoor-led/xrb-outdoor-led-5000nit-lh039xrbcyc-xs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5903" started-at="2024-04-26T20:14:05 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:11 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/2021-the-wall-lh012iwamws-xu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3538" started-at="2024-04-26T20:14:11 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:14 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/2021-the-wall-lh008iwamws-xu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5606" started-at="2024-04-26T20:14:14 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:20 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/led-signage/the-wall/2021-the-wall-lh016iwamws-xu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="9715" started-at="2024-04-26T20:14:20 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:29 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vh55r-r-lh55vhrrbgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3994" started-at="2024-04-26T20:14:29 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:33 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-e-fhd-1080p-500nit-ip5x-174mm-lh55vmbebgbxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-e-fhd-1080p-500nit-ip5x-174mm-lh55vmbebgbxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-e-fhd-1080p-500nit-ip5x-174mm-lh55vmbebgbxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5870" started-at="2024-04-26T20:14:33 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:39 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-ds-3000nit-24hr-ip5x-double-sided-lh55omndsgbxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-ds-3000nit-24hr-ip5x-double-sided-lh55omndsgbxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/omn-ds-3000nit-24hr-ip5x-double-sided-lh55omndsgbxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3258" started-at="2024-04-26T20:14:39 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:43 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/video-wall/vmb-u-fhd-1080p-500nit-ip5x-35mm-lh46vmbubgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3760" started-at="2024-04-26T20:14:43 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:46 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/outdoor-signage/outdoor-signage-oh24b-fhd-1500nit-ip66-lh24ohbebgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3792" started-at="2024-04-26T20:14:46 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:50 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qbr-t-fhd-1080p-capacitive-touch-14ms-lh24qbrtbgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qbr-t-fhd-1080p-capacitive-touch-14ms-lh24qbrtbgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qbr-t-fhd-1080p-capacitive-touch-14ms-lh24qbrtbgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3750" started-at="2024-04-26T20:14:50 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:54 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/sh37r-b-700nit-lh37shrbbgbxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3356" started-at="2024-04-26T20:14:54 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:14:57 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb13r-tm-13-full-hd-interactive-display-fhd-1080p-capacitive-touch-14ms-lh13qbrtmgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb13r-tm-13-full-hd-interactive-display-fhd-1080p-capacitive-touch-14ms-lh13qbrtmgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/interactive-display/qb13r-tm-13-full-hd-interactive-display-fhd-1080p-capacitive-touch-14ms-lh13qbrtmgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3702" started-at="2024-04-26T20:14:57 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:01 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/others/qbr-m-13-full-hd-small-display-lh13qbrmbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4194" started-at="2024-04-26T20:15:01 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:05 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qm85r-b-uhd-4k-500nit-ip5x-lh85qmrbbgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3647" started-at="2024-04-26T20:15:05 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:09 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qb85r-b-uhd-4k-350nit-ip5x-lh85qbrbdgcxxs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4345" started-at="2024-04-26T20:15:09 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:13 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh65qhbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh65qhbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh65qhbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3503" started-at="2024-04-26T20:15:13 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:17 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh55qhbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh55qhbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh55qhbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3331" started-at="2024-04-26T20:15:17 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:20 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh43qhbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh43qhbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh43qhbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="4665" started-at="2024-04-26T20:15:20 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:25 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh75qhbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh75qhbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh75qhbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3285" started-at="2024-04-26T20:15:25 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:28 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh50qhbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh50qhbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qhb-quantum-processor-4k-signage-lh50qhbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5075" started-at="2024-04-26T20:15:28 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:33 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh55qmbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh55qmbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh55qmbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="7628" started-at="2024-04-26T20:15:33 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:41 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh43qmbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh43qmbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh43qmbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3443" started-at="2024-04-26T20:15:41 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:44 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh65qmbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh65qmbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh65qmbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="5178" started-at="2024-04-26T20:15:44 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:49 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh75qmbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh75qmbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh75qmbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="FAIL" signature="verifyExistOfMetaContent(java.lang.String)[pri:2, instance:projectss.testcases.MetaTest@5a1c0542]" name="verifyExistOfMetaContent" duration-ms="3962" started-at="2024-04-26T20:15:49 ICT" data-provider="qaURLs" finished-at="2024-04-26T20:15:53 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh50qmbebgcxxs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh50qmbebgcxxs expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail URL: https://p6-qa.samsung.com/my/business/smart-signage/uhd-4k-signage/qmb-quantum-processor-4k-signage-lh50qmbebgcxxs expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectss.testcases.MetaTest.verifyExistOfMetaContent(MetaTest.java:122)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyExistOfMetaContent -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:projectss.testcases.MetaTest@5a1c0542]" name="tearDown" is-config="true" duration-ms="2894" started-at="2024-04-26T20:15:53 ICT" finished-at="2024-04-26T20:15:56 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- projectss.testcases.MetaTest -->
    </test> <!-- AutomationTest -->
  </suite> <!-- PageObjectTest Example -->
</testng-results>
